import { Poppins } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Link from "next/link";

const poppins = Poppins({
  weight: ["300", "400", "600", "700", "800"],
  subsets: ["latin"],
});
export const metadata = {
  title: "Maids",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <Link rel="icon" href="/img/favicon.jpg" />
      </Head>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
